sudo: required
services:
  - docker

berore_install:
  - docker build -f Dockerfile.dev -t ndonova/test-docker-react-app .
scripts:
  - docker run ndonova/test-docker-react-app npm run test -- --covarage